from OpenGL.GLUT import *

# Control keys
SWAP = GLUT_KEY_UP
LEFT = GLUT_KEY_LEFT
RIGHT = GLUT_KEY_RIGHT
DOWN = GLUT_KEY_DOWN
HARD_DROP = b' '
ROTATE90 = b'r'
ROTATE180 = b'w'
ROTATE270 = b'e'
RESTART = b'g'